EDUHOME/EDUHOME/Areas/Admin/Controllers/CoursesController.cs
using Allup.Data;
using EDUHOME.Areas.Admin.Data;
using EDUHOME.Areas.Admin.Models;
using EDUHOME.DAL;
using EDUHOME.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuGet.DependencyResolver;
using System.Xml.Linq;

namespace EDUHOME.Areas.Admin.Controllers
{
    public class CoursesController : BaseController
    {
        private readonly AppDbContext _dbContext;

        public CoursesController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public async Task<IActionResult> Index()
        {
            var courses = await _dbContext.Courses
                .Include(category => category.Category)
                .ToListAsync();

            return View(courses);
        }

        public async Task<IActionResult> Create()
        {
            var categories = await _dbContext.Categories
                .Where(categorie => !categorie.IsDeleted)
                .ToListAsync();

            var categoriesSelectedListItem = new List<SelectListItem>();

            categories.ForEach(category => categoriesSelectedListItem.Add(new SelectListItem(category.Name, category.Id.ToString())));

            var model = new CourseCreateViewModel
            {
                Categories = categoriesSelectedListItem,
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CourseCreateViewModel model)
        {
            var categories = await _dbContext.Categories
                .Where(categorie => !categorie.IsDeleted)
                .ToListAsync();

            var categoriesSelectedListItem = new List<SelectListItem>();

            categories.ForEach(category => categoriesSelectedListItem.Add(new SelectListItem(category.Name, category.Id.ToString())));

            var viewMmodel = new CourseCreateViewModel
            {
                Categories = categoriesSelectedListItem,
            };

            if (ModelState.IsValid) return View(viewMmodel);

            if (!model.Image.IsImage())
            {
                ModelState.AddModelError("Image", "Shekil Secmelisiz");
                return View(viewMmodel);
            }

            if (!model.Image.IsAllowedSize(10))
            {
                ModelState.AddModelError("Image", "Shekilin olcusu 10 mbdan az omalidi");
                return View(viewMmodel);
            }

            var unicalName = await model.Image.GenerateFile(Constants.CoursePath);

            var course = new Course
            {
                Name = model.Name,
                Content = model.Content,
                About = model.About,
                Apply = model.Apply,
                Certification = model.Certification,
                Reply = model.Reply,
                GeginningTime = model.GeginningTime,
                Duration = model.Duration,
                ClassDuration = model.ClassDuration,
                Level = model.Level,
                Language = model.Language,
                StudentsCount = model.StudentsCount,
                Assesments = model.Assesments,
                Fee = model.Fee,
                ImageUrl = unicalName,
                CategoryId = model.CategoryId,
            };

            await _dbContext.Courses.AddAsync(course);

            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int id)
        {
            var categories = await _dbContext.Categories
                .Where(categorie => !categorie.IsDeleted)
                .ToListAsync();

            var categoriesSelectedListItem = new List<SelectListItem>();

            categories.ForEach(category => categoriesSelectedListItem.Add(new SelectListItem(category.Name, category.Id.ToString())));

            var course = await _dbContext.Courses
                .Where(course => course.Id == id)
                .FirstOrDefaultAsync();

            var model = new CourseUpdateViewModel
            {
                Name = course.Name,
                Content = course.Content,
                About = course.About,
                Apply = course.Apply,
                Certification = course.Certification,
                Reply = course.Reply,
                GeginningTime = course.GeginningTime,
                Duration = course.Duration,
                ClassDuration = course.ClassDuration,
                Level = course.Level,
                Language = course.Language,
                StudentsCount = course.StudentsCount,
                Assesments = course.Assesments,
                Fee = course.Fee,
                ImageUrl = course.ImageUrl,
                CategoryId = course.CategoryId,
                Categories = categoriesSelectedListItem,

            };

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, CourseUpdateViewModel model)
        {
            if (id == null) return BadRequest();

            var existCourse = await _dbContext.Courses
                .Where(course => course.Id == id)
                .FirstOrDefaultAsync();

            if (existCourse == null) return BadRequest();

            var categories = await _dbContext.Categories
                .Where(categorie => !categorie.IsDeleted)
                .ToListAsync();

            var categoriesSelectedListItem = new List<SelectListItem>();

            categories.ForEach(category => categoriesSelectedListItem.Add(new SelectListItem(category.Name, category.Id.ToString())));

            var viewModel = new CourseUpdateViewModel
            {
                Categories = categoriesSelectedListItem,
            };

            if (!ModelState.IsValid) return View(viewModel);

            if (model.Image != null)
            {
                if (!model.Image.IsImage())
                {
                    ModelState.AddModelError("Image", "Shekil Secmelisiz");
                    return View(viewModel);
                }

                if (!model.Image.IsAllowedSize(10))
                {
                    ModelState.AddModelError("Image", "Shekilin olcusu 10 mbdan az omalidi");
                    return View(viewModel);
                }

                var path = Path.Combine(Constants.RootPath, "assets", "images", "course", existCourse.ImageUrl);

                if (System.IO.File.Exists(path))
                    System.IO.File.Delete(path);

                var unicalName = await model.Image.GenerateFile(Constants.CoursePath);

                existCourse.ImageUrl = unicalName;
            }

            existCourse.Name = model.Name;
            existCourse.Content = model.Content;
            existCourse.About = model.About;
            existCourse.Apply = model.Apply;
            existCourse.Certification = model.Certification;
            existCourse.Reply = model.Reply;
            existCourse.GeginningTime = model.GeginningTime;
            existCourse.Duration = model.Duration;
            existCourse.ClassDuration = model.ClassDuration;
            existCourse.Level = model.Level;
            existCourse.Language = model.Language;
            existCourse.StudentsCount = model.StudentsCount;
            existCourse.Assesments = model.Assesments;
            existCourse.Fee = model.Fee;          
            existCourse.CategoryId = model.CategoryId;

            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return BadRequest();

            var existCourse = await _dbContext.Courses
                .Where(course => course.Id == id)
                .FirstOrDefaultAsync();

            if (existCourse == null) return BadRequest();

            _dbContext.Courses.Remove(existCourse);

            var path = Path.Combine(Constants.RootPath, "assets", "images", "course", existCourse.ImageUrl);

            if (System.IO.File.Exists(path))
                System.IO.File.Delete(path);

            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

EDUHOME/EDUHOME/Controllers/CoursesController.cs
using EDUHOME.DAL;
using EDUHOME.DAL.Entities;
using EDUHOME.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EDUHOME.Controllers
{
    public class CoursesController : Controller
    {
        private readonly AppDbContext _dbContext;
 
        public CoursesController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            var course = await _dbContext.Courses
                .Where(course => !course.IsDeleted)
                .ToListAsync();

            var model = new List<CourseViewModel>();

            course.ForEach(course => model.Add(new CourseViewModel
            {
                Id = course.Id,
                Name = course.Name,
                Content = course.Content,
                About = course.About,
                Apply = course.Apply,
                Certification = course.Certification,
                Reply = course.Reply,
                GeginningTime = course.GeginningTime,
                Duration = course.Duration,
                ClassDuration = course.ClassDuration,
                Level = course.Level,
                Language = course.Language,
                StudentsCount = course.StudentsCount,
                Assesments = course.Assesments,
                Fee= course.Fee,
                ImageUrl = course.ImageUrl,

            }));

            return View(model);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var course = await _dbContext.Courses
                .Where(blog => blog.Id == id)
                .FirstOrDefaultAsync();

            if (course == null) return NotFound();

            var model = new CourseViewModel
            {
                Name = course.Name,
                Content = course.Content,
                About = course.About,
                Apply = course.Apply,
                Certification = course.Certification,
                Reply = course.Reply,
                GeginningTime = course.GeginningTime,
                Duration = course.Duration,
                ClassDuration = course.ClassDuration,
                Level = course.Level,
                Language = course.Language,
                StudentsCount = course.StudentsCount,
                Assesments = course.Assesments,
                Fee = course.Fee,
                ImageUrl = course.ImageUrl,
            };    
      
            return View(model);
        }
    }
}

EDUHOME/EDUHOME/ViewComponents/DetailsSidebarViewComponent.cs
using EDUHOME.DAL;
using EDUHOME.DAL.Entities;
using EDUHOME.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EDUHOME.ViewComponents
{
    public class DetailsSidebarViewComponent : ViewComponent
    {
        private readonly AppDbContext _dbContext;

        public DetailsSidebarViewComponent(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _dbContext.Categories
                .Where(category=>!category.IsDeleted)
                .Include(x=>x.Courses)
                .ToListAsync();

            var blogs = await _dbContext.Blogs
                .Where(blog => !blog.IsDeleted)
                .OrderByDescending(blog => blog.Id)
                .Take(3)
                .ToListAsync();

            var model = new DetailsSidebarViewModel
            {
                Categories = categories,
                Blogs = blogs,
            };

            return View(model);
        }
    }
}

EDUHOME/EDUHOME/Views/Courses/Details.cshtml
@model CourseViewModel
@{
    var course = Model;
}
<!-- Banner Area Start -->
<div class="banner-area-wrapper">
    <div class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="banner-content-wrapper">
                        <div class="banner-content">
                            <h2>courses details</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Area End -->
<!-- Blog Start -->
<div class="courses-details-area blog-area pt-150 pb-140">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="courses-details">
                    <div class="courses-details-img">
                        <img src="~/assets/images/course/@course.ImageUrl" alt="courses-details">
                    </div>
                    <div class="course-details-content">
                        <h2>@course.Name</h2>
                        <p>@course.Content</p>
                        <div class="course-details-left">
                            <div class="single-course-left">
                                <h3>about course</h3>
                                <p>@course.Apply</p>
                            </div>
                            <div class="single-course-left">
                                <h3>how to apply</h3>
                                <p>@course.Apply</p>
                            </div>
                            <div class="single-course-left">
                                <h3>certification</h3>
                                <p class="margin">@course.Certification</p>
                                
                            </div>
                        </div>
                        <div class="course-details-right">
                            <h3>COURSE FEATURES</h3>
                            <ul>
                                <li>starts <span>@course.GeginningTime</span></li>
                                <li>duration <span>@course.Duration Month</span></li>
                                <li>class duration <span>@course.ClassDuration hours</span></li>
                                <li>skill level <span>@course.Level</span></li>
                                <li>language <span>@course.Language</span></li>
                                <li>students <span>@course.StudentsCount</span></li>
                                <li>assesments <span>@course.Assesments</span></li>
                            </ul>
                            <h3 class="red">course fee @course.Fee</h3>
                        </div>
                    </div>
                    <div class="reply-area">
                        <h3>LEAVE A REPLY</h3>
                        <p>@course.Reply </p>
                        <form id="contact-form" action="http://demo.devitems.com/eduhome/mail.php" method="post">
                            <div class="row">
                                <div class="col-md-12">
                                    <p>Name</p>
                                    <input type="text" name="name" id="name">
                                </div>
                                <div class="col-md-12">
                                    <p>Email</p>
                                    <input type="text" name="email" id="email">
                                </div>
                                <div class="col-md-12">
                                    <p>Subject</p>
                                    <input type="text" name="subject" id="subject">
                                    <p>Massage</p>
                                    <textarea name="message" id="message" cols="15" rows="10"></textarea>
                                </div>
                            </div>
                            <a class="reply-btn" href="#" data-text="send"><span>send message</span></a>
                            <p class="form-messege"></p>
                        </form>
                    </div>
                </div>
            </div>
            @await Component.InvokeAsync("DetailsSidebar")
        </div>
    </div>
</div>
<!-- Blog End -->
<!-- Subscribe Start -->
<div class="subscribe-area pt-60 pb-70">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="subscribe-content section-title text-center">
                    <h2>subscribe our newsletter</h2>
                    <p>I must explain to you how all this mistaken idea </p>
                </div>
                <div class="newsletter-form mc_embed_signup">
                    <form action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                        <div id="mc_embed_signup_scroll" class="mc-form">
                            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Enter your e-mail address" required>
                            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                            <div class="mc-news" aria-hidden="true"><input type="text" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef" tabindex="-1" value=""></div>
                            <button id="mc-embedded-subscribe" class="default-btn" type="submit" name="subscribe"><span>subscribe</span></button>
                        </div>
                    </form>
                    <!-- mailchimp-alerts Start -->
                    <div class="mailchimp-alerts">
                        <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                        <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                        <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                    </div>
                    <!-- mailchimp-alerts end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Subscribe End -->

EDUHOME/EDUHOME/Views/Courses/Index.cshtml
@model List<CourseViewModel>
<!-- Banner Area Start -->
<div class="banner-area-wrapper">
    <div class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="banner-content-wrapper">
                        <div class="banner-content">
                            <h2>courses</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Area End -->
<!-- Course Start -->
<div class="course-area pt-150 pb-150">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="course-title">
                    <h3>search courses</h3>
                </div>
                <div class="course-form">
                    <form id="search" action="#">
                        <input type="search" placeholder="Search..." name="search" />
                        <button type="submit">search</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">

            @foreach (var item in Model)
            {
                <partial name="_CourseItemPartial" model="item" />
            }
        </div>
    </div>
</div>
<!-- Course End -->
<!-- Subscribe Start -->
<div class="subscribe-area pt-60 pb-70">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="subscribe-content section-title text-center">
                    <h2>subscribe our newsletter</h2>
                    <p>I must explain to you how all this mistaken idea </p>
                </div>
                <div class="newsletter-form mc_embed_signup">
                    <form action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                        <div id="mc_embed_signup_scroll" class="mc-form">
                            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Enter your e-mail address" required>
                            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                            <div class="mc-news" aria-hidden="true"><input type="text" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef" tabindex="-1" value=""></div>
                            <button id="mc-embedded-subscribe" class="default-btn" type="submit" name="subscribe"><span>subscribe</span></button>
                        </div>
                    </form>
                    <!-- mailchimp-alerts Start -->
                    <div class="mailchimp-alerts">
                        <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                        <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                        <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                    </div>
                    <!-- mailchimp-alerts end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Subscribe End -->